[connections.supabase]
SUPABASE_URL = "https://bbboysoishrtdbotryly.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYm95c29pc2hydGRib3RyeWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcyNjg5ODgsImV4cCI6MjA4Mjg0NDk4OH0.Ldz8c3TU_tdHnNRYnWu3_SBa72lEZTWkyhh3HWZVbac"

STRAVA_CLIENT_ID = "192959"
STRAVA_CLIENT_SECRET = "858ac2eec91666cda490f41177a2ed85b68f3825"
STRAVA_REDIRECT_URI = "http://localhost:8501"


