[connections.supabase]
SUPABASE_URL = "https://bbboysoishrtdbotryly.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYm95c29pc2hydGRib3RyeWx5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NzI2ODk4OCwiZXhwIjoyMDgyODQ0OTg4fQ.wRz4PVVlcOsJStS5Flj-IK-o5iaB-6qm1gJ4AoU5i-A"

STRAVA_CLIENT_ID = "192959"
STRAVA_CLIENT_SECRET = "858ac2eec91666cda490f41177a2ed85b68f3825"
STRAVA_REDIRECT_URI = "http://localhost:8501"


